In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("D:/download/customer_shopping_behavior.csv")

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [7]:
df.columns=df.columns.str.lower()

In [8]:
df.columns=df.columns.str.replace(" ","_")

In [9]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [10]:
df.columns=df.columns.str.replace('purchase_amount_(usd)','purchase_amount')

In [11]:
df.isnull().sum()

customer_id                0
age                        0
gender                     0
item_purchased             0
category                   0
purchase_amount            0
location                   0
size                       0
color                      0
season                     0
review_rating             37
subscription_status        0
shipping_type              0
discount_applied           0
promo_code_used            0
previous_purchases         0
payment_method             0
frequency_of_purchases     0
dtype: int64

In [12]:
df['review_rating']=df.groupby('category')['review_rating'].transform(lambda x: x.fillna(x.median()))

In [13]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [14]:
#age group column 
labels=['young adult','adult','middle-aged','senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [15]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [16]:
#purches frequency days column creation 
frequency_mapping={'Fortnightly':14,'Weekly':7, 'Annually':365, 'Quarterly':90, 'Bi-Weekly':14,
       'Monthly':30, 'Every 3 Months' :90}
df['purches_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [17]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [18]:
 df=df.drop('promo_code_used', axis=1)

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purches_frequency_days'],
      dtype='object')

In [20]:
# connection with MySQL
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in .\AppData\Roaming\Python\Python312\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python312\site-packages (1.4.54)
Requirement already satisfied: greenlet!=0.4.17 in .\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (3.4.0)

WARNING: Ignoring invalid distribution ~andas (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)

In [21]:
pip install "sqlalchemy<2.0" pymysql

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: sqlalchemy<2.0 in .\AppData\Roaming\Python\Python312\site-packages (1.4.54)
Requirement already satisfied: pymysql in .\AppData\Roaming\Python\Python312\site-packages (1.1.2)
Requirement already satisfied: greenlet!=0.4.17 in .\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy<2.0) (3.4.0)

WARNING: Ignoring invalid distribution ~andas (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~andas (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~orch (C:\Users\sachi\AppData\Roaming\Python\Python312\site-packages)

In [22]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:123@localhost:3306/customer_behavior"
)


# 🔹 Drop old table (important to avoid mismatch)
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS customer"))

# 🔹 Create table dynamically from your df
columns = ", ".join([f"`{col}` TEXT" for col in df.columns])

with engine.connect() as conn:
    conn.execute(text(f"CREATE TABLE customer ({columns})"))

# 🔹 Insert all data
data = df.to_dict(orient="records")

with engine.begin() as conn:
    conn.execute(
        text(f"""
            INSERT INTO customer ({', '.join([f"`{col}`" for col in df.columns])})
            VALUES ({', '.join([f":{col}" for col in df.columns])})
        """),
        data
    )

print("✅ Original data inserted successfully")

C:\Users\sachi\AppData\Local\Temp\ipykernel_22888\158294352.py:10: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  conn.execute(text("DROP TABLE IF EXISTS customer"))

✅ Original data inserted successfully

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purches_frequency_days'],
      dtype='object')